export async function predictTimeline(
    fileOrText: File | string,
    contentType: string,
    instructions?: string
  ) {
    console.log("Summarizing with:", { fileOrText, contentType, instructions })
  
    return {
      summary: "This is a mock summary generated by Gemini.",
      paperTitle: "Untitled Document",
      status: "success",
    }
  }
  